logging:
    level:
        org:
            springframework:
                security: trace
spring:
    security:
        oauth2:
            authorizationserver:
                client:
                    client-1:
                        registration:
                            authorization-grant-types: client_credentials
                            client-authentication-methods: client_secret_basic
                            client-id: admin-client
                            client-secret: '{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC'
                            scopes: user.read,user.write
                        token:
                            access-token-time-to-live: 120s
